
# ── Flaky test quarantine (auto-generated by FlakyRegistry) ──────────
import pytest
from pathlib import Path
from src.flaky.registry import FlakyRegistry

_FLAKY_REGISTRY = FlakyRegistry(Path("data/flaky_registry.json"))

def pytest_collection_modifyitems(items, config):
    """Tag known-flaky tests so they can be excluded from blocking CI."""
    flaky_marker = pytest.mark.flaky
    for item in items:
        if _FLAKY_REGISTRY.is_flaky(item.nodeid):
            item.add_marker(flaky_marker, append=False)

# Run without flaky tests:  pytest -m "not flaky"
# Run only flaky tests:     pytest -m "flaky"
# ─────────────────────────────────────────────────────────────────────
